package:
  name: autocnet
  version: 0.2.5
  
channels:
  - conda-forge
  - menpo
  - usgs-astrogeology
  
source:
   git_url: https://github.com/USGS-Astrogeology/autocnet.git
   git_rev: dev

requirements:
  build:
    - python=3
    - numpy                                                                          
    - scipy                                                                          
    - scikit-image                                                                   
    - opencv                                                                         
    - vlfeat                                                                         
    - cyvlfeat                                                                       
    - csmapi                                                                         
    - networkx                                                                       
    - pillow                                                                         
    - plio                                                                           
    - ncurses                                                                        
    - geopandas
    - imageio
  run:
    - python=3
    - numpy                                                                          
    - scipy                                                                          
    - scikit-image                                                                   
    - opencv                                                                         
    - vlfeat                                                                         
    - cyvlfeat                                                                       
    - csmapi                                                                         
    - networkx                                                                       
    - pillow                                                                         
    - plio                                                                           
    - ncurses                                                                        
    - geopandas
    - imageio
    - pysis
test:
  imports:
    - autocnet
    - autocnet.graph.network
